dbt_on_gcp:
  outputs:
    dev:
      dataset: raw
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: adilton
      threads: 8
      type: bigquery
  target: dev
